# Header
menu:
  Home: /
  Archives: /archives
  RSS: /atom.xml

feed:
  type: atom
  path: atom.xml
  limit: 20

## hexo-generator-sitemap (https://github.com/hexojs/hexo-generator-sitemap)
sitemap:
  path: sitemap.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
